### ISSUE TITLE
Pass in false to remove option

### ISSUE THREAD

**Issue by mech** [abaddonGIT/react-paginator-box#8]
If we do not want the `firstText`, will it be nicer to pass it a `false` value to totally remove it?

Like:

`<PaginationBox firstText={false} lastText={fasle} />`

**Comment by mech** [comment]
Also I am puzzle on why `angularLink` for a react component, hmms...

**Comment by abaddonGIT** [comment]
This a good idea:
`<PaginationBox firstText={false} lastText={fasle} />`
I add this in next reliz. Thanks.

**Comment by abaddonGIT** [comment]
And i check angularLink props.

**Comment by mech** [comment]
Sorry did not read carefully, it was done by using `edgeLinks`. Close it now!
