### ISSUE TITLE
When at ?page=2 and do a hard refresh the paginator change to page 1

### ISSUE THREAD

**Issue by mech** [abaddonGIT/react-paginator-box#9]
Hi, when I do a hard refresh at page=2, the paginator-box component goes back to page=1.

**Comment by abaddonGIT** [comment]
Show your component call and input parameters pls.

**Comment by mech** [comment]
Hi, I called the component like this:

```
<PaginationBox
            startPage={this.startPage.bind(this)}
            edgeLinks={false}
            hrefPrefix={`?q=${this.state.searchString}&page`}
            items={this.state.total_count}
            limit={this.state.per_page}
            selectHandler={this.page.bind(this)} />
```

The `startPage` function is exactly like what was on the README.

When clicking on the component itself, the page number and URL changes, no issues. But when doing a hard refresh on the browser, the component jump to page=1 :(

**Comment by mech** [comment]
Here a demo of it

![demo1](https://cloud.githubusercontent.com/assets/5850/9928574/b875255a-5d59-11e5-8e27-589b7ebd6153.gif)

**Comment by abaddonGIT** [comment]
You url is complicated than in example and you need change startPage function like that:

```
startPage: function () {
        var loc = window.location.href, search = loc ? loc.split('=') : 0;
        return search[2] ? search[2] : 1;
    }
```

**Comment by mech** [comment]
No luck on that. It seems that the `startPage` function is not being called. I have remove the function body and just include a `console.log` and can confirm that `startPage` was not called either during paging or refreshing.

**Comment by abaddonGIT** [comment]
I find problem. I'll try to fix it soon

**Comment by mech** [comment]
:+1:

**Comment by abaddonGIT** [comment]
I update npm package. Now it should work correctly. But you still have to use the second variant startPage.

**Comment by mech** [comment]
Tks for the fix!
